[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "organize"
version = "0.1.0"
description = "Ferramenta CLI para organizar arquivos por categoria"
authors = [
    { name = "Erik" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"

[project.scripts]
organize = "organize.cli:main"